version: '3'
services:
  opencr:
    container_name: opencr
    image: intrahealth/opencr
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - es
    environment:
      - NODE_ENV=docker
    networks:
      - hienet

  es:
    container_name: es
    image: intrahealth/elasticsearch:latest
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - hienet
      
volumes:
  opencrs_data:
    driver: local
    
networks:
  hienet:
    name: hienet
    external: true